#module definition
#Mon Nov 10 14:32:43 CET 2014
projects=gradle-base-services
runtime=slf4j-api-1.7.7.jar,guava-jdk5-17.0.jar,kryo-2.20.jar,asm-all-5.0.3.jar,reflectasm-1.07-shaded.jar,minlog-1.2.jar,objenesis-1.2.jar
