buildNumber=none
buildTimestamp=20141110133144+0000
commitId=aab8521f1fd9a3484cac18123a72bcfdeb7006ec
hostname=dev1.gradle.org
isSnapshot=false
javaVersion=1.7.0_02
osName=Linux
osVersion=3.2.0-57-generic
project=gradle
rcNumber=
username=tcagent1
versionBase=2.2
versionNumber=2.2